services:

  scraper:
    build: { context: ., dockerfile: Dockerfile, args: SCRAPER_COMMAND: ${SCRAPER_COMMAND:-test} }
    env_file: .env
    dns: [8.8.8.8, 1.1.1.1]
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - ./output:/scraper/output
      - /tmp/.X11-unix:/tmp/.X11-unix
    stop_signal: SIGINT
    stop_grace_period: 5s
